import { Card } from "../app/core/model/card.model";

export const drsCards: Card[] = [
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "hero",
        "type_name": "Hero",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "linked_to_code": "09001b",
        "linked_to_name": "Stephen Strange",
        "position": 1,
        "code": "09001a",
        "name": "Doctor Strange",
        "real_name": "Doctor Strange",
        "text": "<i>Spell Mastery</i> — <b>Action</b>: Exhaust Doctor Strange and pay the cost of the top card of the [[Invocation]] deck → resolve the \"<b>Special</b>\" ability on that card.",
        "real_text": "<i>Spell Mastery</i> — <b>Action</b>: Exhaust Doctor Strange and pay the cost of the top card of the [[Invocation]] deck → resolve the \"<b>Special</b>\" ability on that card.",
        "quantity": 1,
        "hand_size": 5,
        "health": 10,
        "health_per_hero": false,
        "thwart": 2,
        "attack": 1,
        "defense": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Avenger. Mystic.",
        "real_traits": "Avenger. Mystic.",
        "meta": {
            "colors": [
                "#797c81",
                "#841519",
                "#beaa6a",
                "#fffffd"
            ],
            "offset": "-50px -43px"
        },
        "flavor": "\"By the Hoary Hosts of Hoggoth!\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "81d1cf04-43ab-4817-8746-18995bc7ddca",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09001a",
        "imagesrc": "/bundles/cards/09001a.png",
        "linked_card": {
            "pack_code": "drs",
            "pack_name": "Doctor Strange",
            "type_code": "alter_ego",
            "type_name": "Alter-Ego",
            "faction_code": "hero",
            "faction_name": "Hero",
            "card_set_code": "doctor_strange",
            "card_set_name": "Doctor Strange",
            "card_set_type_name_code": "hero",
            "id": 454,
            "position": 1,
            "set_position": null,
            "code": "09001b",
            "name": "Stephen Strange",
            "real_name": "Stephen Strange",
            "subname": null,
            "cost": null,
            "text": "<p>Stephen Strange begins the game with an <b class=\"card-traits\"><i>Invocation</i></b> deck. (See insert.)</p><p><i>Natural Talent</i> — <b>Action</b>: Discard the top card of the <b class=\"card-traits\"><i>Invocation</i></b> deck. (Limit once per phase.)</p>",
            "real_text": "Stephen Strange begins the game with an [[Invocation]] deck. (See insert.)\n<i>Natural Talent</i> — <b>Action</b>: Discard the top card of the [[Invocation]] deck. (Limit once per phase.)",
            "boost": null,
            "quantity": 1,
            "resource_energy": null,
            "resource_physical": null,
            "resource_mental": null,
            "resource_wild": null,
            "hand_size": 6,
            "health": 10,
            "health_per_hero": false,
            "thwart": null,
            "thwart_cost": null,
            "scheme": null,
            "attack": null,
            "attack_cost": null,
            "defense": null,
            "defense_cost": null,
            "recover": 3,
            "recover_cost": null,
            "base_threat": null,
            "base_threat_fixed": false,
            "escalation_threat": null,
            "escalation_threat_fixed": false,
            "scheme_crisis": null,
            "scheme_acceleration": null,
            "scheme_hazard": null,
            "threat": null,
            "threat_fixed": false,
            "deck_limit": 1,
            "stage": null,
            "traits": "Mystic.",
            "real_traits": "Mystic.",
            "meta": null,
            "deck_requirements": null,
            "deck_options": null,
            "restrictions": null,
            "flavor": "",
            "illustrator": null,
            "is_unique": true,
            "hidden": true,
            "permanent": false,
            "double_sided": false,
            "back_text": null,
            "back_flavor": null,
            "back_name": null,
            "octgn_id": "81d1cf04-43ab-4817-8746-18995bc7ddca",
            "attack_star": false,
            "thwart_star": false,
            "defense_star": false,
            "health_star": false,
            "recover_star": false,
            "scheme_star": false,
            "boost_star": false,
            "threat_star": false,
            "escalation_threat_star": false,
            "url": "https://marvelcdb.com/card/09001b",
            "imagesrc": "/bundles/cards/09001b.png",
            "backimagesrc": null
        }
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 2,
        "set_position": 1,
        "code": "09002",
        "name": "Wong",
        "real_name": "Wong",
        "cost": 3,
        "text": "<b>Action</b>: Exhaust Wong → choose to either heal 1 damage from your identity or discard the top card of the [[Invocation]] deck.",
        "real_text": "<b>Action</b>: Exhaust Wong → choose to either heal 1 damage from your identity or discard the top card of the [[Invocation]] deck.",
        "quantity": 1,
        "resource_wild": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 1,
        "thwart_cost": 1,
        "attack": 2,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Mystic.",
        "real_traits": "Mystic.",
        "flavor": "\"The oath I swore to protect my master overrides all other directives.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "08955fc9-6ba1-4b44-83b2-edcf706bf08e",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09002",
        "imagesrc": "/bundles/cards/09002.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 3,
        "set_position": 2,
        "code": "09003",
        "name": "Astral Projection",
        "real_name": "Astral Projection",
        "cost": 2,
        "text": "<b>Hero Action</b> <i>(thwart)</i>: Choose a scheme → remove 3 threat from that scheme and look at the top card of the encounter deck. For each boost icon on that card, remove 1 additional threat from the chosen scheme.",
        "real_text": "<b>Hero Action</b> <i>(thwart)</i>: Choose a scheme → remove 3 threat from that scheme and look at the top card of the encounter deck. For each boost icon on that card, remove 1 additional threat from the chosen scheme.",
        "quantity": 2,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "traits": "Spell. Thwart.",
        "real_traits": "Spell. Thwart.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "e0731562-32cd-4ecf-aa7b-4f85eb7ecbc3",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09003",
        "imagesrc": "/bundles/cards/09003.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 4,
        "set_position": 4,
        "code": "09004",
        "name": "Magic Blast",
        "real_name": "Magic Blast",
        "cost": 3,
        "text": "<b>Hero Action</b> <i>(attack)</i>: Deal 5 damage to an enemy and discard the top card of your deck. If that card's printed resource has:\n[physical] - Stun that enemy.\n[energy] - Deal 2 damage to that enemy.\n[mental] - Confuse that enemy.\n[wild] - All of the above.",
        "real_text": "<b>Hero Action</b> <i>(attack)</i>: Deal 5 damage to an enemy and discard the top card of your deck. If that card's printed resource has:\n[physical] - Stun that enemy.\n[energy] - Deal 2 damage to that enemy.\n[mental] - Confuse that enemy.\n[wild] - All of the above.",
        "quantity": 2,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "traits": "Attack. Spell.",
        "real_traits": "Attack. Spell.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "2f1acd98-4565-43f7-a9ef-f8025368a421",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09004",
        "imagesrc": "/bundles/cards/09004.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 5,
        "set_position": 6,
        "code": "09005",
        "name": "Master of the Mystic Arts",
        "real_name": "Master of the Mystic Arts",
        "cost": 1,
        "text": "<b>Hero Action</b>: Pay the printed cost of the top card of the [[Invocation]] deck → resolve its \"<b>Special</b>\" ability. Then, place it back on top of the [[Invocation]] deck faceup.",
        "real_text": "<b>Hero Action</b>: Pay the printed cost of the top card of the [[Invocation]] deck → resolve its \"<b>Special</b>\" ability. Then, place it back on top of the [[Invocation]] deck faceup.",
        "quantity": 2,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "flavor": "\"Nothing is impossible for the Sorcerer Supreme!\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "a1b123c8-8b31-45dd-a67a-0757993d5872",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09005",
        "imagesrc": "/bundles/cards/09005.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 6,
        "set_position": 8,
        "code": "09006",
        "name": "Mystical Studies",
        "real_name": "Mystical Studies",
        "cost": 1,
        "text": "<b>Alter-Ego Action</b>: Search your deck and discard pile for a Doctor Strange card and add it to your hand. Shuffle your deck.",
        "real_text": "<b>Alter-Ego Action</b>: Search your deck and discard pile for a Doctor Strange card and add it to your hand. Shuffle your deck.",
        "quantity": 1,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "flavor": "\"I believe observation and knowledge must precede action.\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "1af6c0a9-6aad-45f3-b6ed-adc1fef9a7d3",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09006",
        "imagesrc": "/bundles/cards/09006.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 7,
        "set_position": 9,
        "code": "09007",
        "name": "Protective Ward",
        "real_name": "Protective Ward",
        "cost": 1,
        "text": "<b>Hero Interrupt</b>: When a treachery is revealed from the encounter deck, cancel all of its effects and discard it.",
        "real_text": "<b>Hero Interrupt</b>: When a treachery is revealed from the encounter deck, cancel all of its effects and discard it.",
        "quantity": 2,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "flavor": "\"This is one of the first spells I learned.\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "cddf7c90-bd1c-42bb-a47f-c8d5943dfe06",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09007",
        "imagesrc": "/bundles/cards/09007.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 8,
        "set_position": 11,
        "code": "09008",
        "name": "Sanctum Sanctorum",
        "real_name": "Sanctum Sanctorum",
        "cost": 1,
        "text": "<b>Alter-Ego Action</b>: Exhaust Sanctum Sanctorum → shuffle a [[Spell]] card from your discard pile into your deck and draw 1 card.",
        "real_text": "<b>Alter-Ego Action</b>: Exhaust Sanctum Sanctorum → shuffle a [[Spell]] card from your discard pile into your deck and draw 1 card.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Location.",
        "real_traits": "Location.",
        "flavor": "\"A bit ostentatious for Bleecker Street.\" — Zelma Stanton",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "c3e34f43-2ab1-4063-a3f4-79fc96a79e3c",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09008",
        "imagesrc": "/bundles/cards/09008.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 9,
        "set_position": 12,
        "code": "09009",
        "name": "Cloak of Levitation",
        "real_name": "Cloak of Levitation",
        "cost": 2,
        "text": "You gain the [[Aerial]] trait.\n<b>Hero Action</b>: Exhaust Cloak of Levitation → ready Doctor Strange.",
        "real_text": "You gain the [[Aerial]] trait.\n<b>Hero Action</b>: Exhaust Cloak of Levitation → ready Doctor Strange.",
        "quantity": 1,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Artifact. Item.",
        "real_traits": "Artifact. Item.",
        "flavor": "\"If you're gonna call yourself 'The Sorcerer Supreme', then you really should have a flying cloak.\" — Spider-Man",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "c0caf3ba-0baa-4364-a6f7-e7527218392a",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09009",
        "imagesrc": "/bundles/cards/09009.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 10,
        "set_position": 13,
        "code": "09010",
        "name": "Magical Enhancements",
        "real_name": "Magical Enhancements",
        "cost": 1,
        "text": "Play under any player's control.\nYour hero gets +1 THW, +1 ATK, and +1 DEF.\n<b>Forced Interrupt</b>: When the round ends, discard Magical Enhancements.",
        "real_text": "Play under any player's control.\nYour hero gets +1 THW, +1 ATK, and +1 DEF.\n<b>Forced Interrupt</b>: When the round ends, discard Magical Enhancements.",
        "quantity": 2,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "traits": "Condition. Spell.",
        "real_traits": "Condition. Spell.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "d91c62ab-3343-4569-9707-9a1e28ebfcd9",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09010",
        "imagesrc": "/bundles/cards/09010.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 11,
        "set_position": 15,
        "code": "09011",
        "name": "The Eye of Agamotto",
        "real_name": "The Eye of Agamotto",
        "cost": 2,
        "text": "<b>Hero Resource</b>: Exhaust The Eye of Agamotto → generate a [wild] resource.",
        "real_text": "<b>Hero Resource</b>: Exhaust The Eye of Agamotto → generate a [wild] resource.",
        "quantity": 1,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Artifact. Item.",
        "real_traits": "Artifact. Item.",
        "flavor": "\"The Eye of Agamotto will reveal the truth.\" — Doctor Strange",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "807e3d24-b8e8-49ed-a4b7-a21728a22876",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09011",
        "imagesrc": "/bundles/cards/09011.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 12,
        "code": "09012",
        "name": "Brother Voodoo",
        "real_name": "Brother Voodoo",
        "subname": "Jericho Drumm",
        "cost": 3,
        "text": "<b>Response</b>: After Brother Voodoo enters play, search the top 5 cards of your deck for an event card and add it to your hand. Shuffle your deck.",
        "real_text": "<b>Response</b>: After Brother Voodoo enters play, search the top 5 cards of your deck for an event card and add it to your hand. Shuffle your deck.",
        "quantity": 1,
        "resource_mental": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 2,
        "thwart_cost": 2,
        "attack": 1,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Avenger. Mystic.",
        "real_traits": "Avenger. Mystic.",
        "flavor": "\"My name is Jericho Drumm. They call me Brother Voodoo.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "9f38da0e-c873-4a68-869d-760f6c20e692",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09012",
        "imagesrc": "/bundles/cards/09012.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 13,
        "code": "09013",
        "name": "Clea",
        "real_name": "Clea",
        "cost": 2,
        "text": "<b>Interrupt</b>: When Clea is defeated, shuffle her into her owner's deck.",
        "real_text": "<b>Interrupt</b>: When Clea is defeated, shuffle her into her owner's deck.",
        "quantity": 1,
        "resource_physical": 1,
        "health": 2,
        "health_per_hero": false,
        "thwart": 1,
        "thwart_cost": 1,
        "attack": 1,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Mystic.",
        "real_traits": "Mystic.",
        "flavor": "\"I come from what you call the Dark Dimension. I don't frighten easily.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5bdde0e7-90c1-40a4-a973-480ffe6eb02a",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09013",
        "imagesrc": "/bundles/cards/09013.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 14,
        "code": "09014",
        "name": "Iron Fist",
        "real_name": "Iron Fist",
        "subname": "Danny Rand",
        "cost": 4,
        "text": "Iron First enters play with 2 mystic counters on him.\n<b>Response</b>: When Iron Fist attacks an enemy, remove 1 mystic counter from him → stun that enemy and deal 1 damage to it.",
        "real_text": "Iron First enters play with 2 mystic counters on him.\n<b>Response</b>: When Iron Fist attacks an enemy, remove 1 mystic counter from him → stun that enemy and deal 1 damage to it.",
        "quantity": 1,
        "resource_physical": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 1,
        "thwart_cost": 1,
        "attack": 2,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Defender.",
        "real_traits": "Defender.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "7df162e3-e603-4aaf-b56a-48cc10274eb6",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09014",
        "imagesrc": "/bundles/cards/09014.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 15,
        "code": "09015",
        "name": "Desperate Defense",
        "real_name": "Desperate Defense",
        "cost": 1,
        "text": "<b>Hero Interrupt</b> <i>(defense)</i>: When your hero defends against an attack, it gets +2 DEF for that attack. If you take no damage from that attack, ready your hero.",
        "real_text": "<b>Hero Interrupt</b> <i>(defense)</i>: When your hero defends against an attack, it gets +2 DEF for that attack. If you take no damage from that attack, ready your hero.",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Defense.",
        "real_traits": "Defense.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "8bacc1ad-2cd6-485b-9470-81d91ed047e5",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09015",
        "imagesrc": "/bundles/cards/09015.png",
        "duplicated_by": [
            "16013"
        ]
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 16,
        "code": "09016",
        "name": "Momentum Shift",
        "real_name": "Momentum Shift",
        "cost": 2,
        "text": "<b>Hero Action</b> <i>(attack)</i>: Heal 2 damage from your hero → deal 2 damage to an enemy.",
        "real_text": "<b>Hero Action</b> <i>(attack)</i>: Heal 2 damage from your hero → deal 2 damage to an enemy.",
        "quantity": 3,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Attack.",
        "real_traits": "Attack.",
        "flavor": "\"Have a seat!\" — Colleen Wing",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "196aaf1c-4356-4d89-a28a-e9021edf510f",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09016",
        "imagesrc": "/bundles/cards/09016.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "resource",
        "type_name": "Resource",
        "faction_code": "protection",
        "faction_name": "Protection",
        "duplicate_of_code": "01079",
        "duplicate_of_name": "The Power of Protection",
        "position": 17,
        "code": "09017",
        "name": "The Power of Protection",
        "real_name": "The Power of Protection",
        "text": "Max 2 per deck.\nDouble the number of resources this card generates while paying for a Protection <i>(green)</i> card.",
        "real_text": "Max 2 per deck.\nDouble the number of resources this card generates while paying for a Protection <i>(green)</i> card.",
        "quantity": 2,
        "resource_wild": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "a0390985-df47-494a-85fc-f92a83518e34",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09017"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "protection",
        "faction_name": "Protection",
        "duplicate_of_code": "01080",
        "duplicate_of_name": "Med Team",
        "position": 18,
        "code": "09018",
        "name": "Med Team",
        "real_name": "Med Team",
        "cost": 3,
        "text": "Uses (3 medical counters). <i>(Enters play with 3 counters. When those are gone, discard this card.)</i>\n<b>Action</b>: Exhaust Med Team and remove 1 medical counter from it → heal 2 damage from a friendly character.",
        "real_text": "Uses (3 medical counters). <i>(Enters play with 3 counters. When those are gone, discard this card.)</i>\n<b>Action</b>: Exhaust Med Team and remove 1 medical counter from it → heal 2 damage from a friendly character.",
        "quantity": 2,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "S.H.I.E.L.D.",
        "real_traits": "S.H.I.E.L.D.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "b7c500ec-9b58-43cb-9310-0ac806a102c8",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09018"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 19,
        "code": "09019",
        "name": "The Night Nurse",
        "real_name": "The Night Nurse",
        "cost": 1,
        "text": "Uses (3 medical counters).\n<b>Action</b>: Exhaust The Night Nurse and remove 1 medical counter from her → heal 1 damage from a hero and discard 1 status card from it.",
        "real_text": "Uses (3 medical counters).\n<b>Action</b>: Exhaust The Night Nurse and remove 1 medical counter from her → heal 1 damage from a hero and discard 1 status card from it.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Persona.",
        "real_traits": "Persona.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "1518044d-a532-4cfa-aa11-c7f5427ece3e",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09019",
        "imagesrc": "/bundles/cards/09019.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 20,
        "code": "09020",
        "name": "Unflappable",
        "real_name": "Unflappable",
        "cost": 1,
        "text": "Play under any player's control. Max 1 per player.\n<b>Response</b>: After you defend against an attack and take no damage, exhaust Unflappable → draw 1 card.",
        "real_text": "Play under any player's control. Max 1 per player.\n<b>Response</b>: After you defend against an attack and take no damage, exhaust Unflappable → draw 1 card.",
        "quantity": 3,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Condition.",
        "real_traits": "Condition.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "ba1c7989-37c8-46e7-9999-951ae18def3b",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09020",
        "imagesrc": "/bundles/cards/09020.png",
        "duplicated_by": [
            "38013"
        ]
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 21,
        "code": "09021",
        "name": "Warning",
        "real_name": "Warning",
        "cost": 0,
        "text": "<b>Interrupt</b> <i>(defense)</i>: When a hero would take any amount of damage, reduce that amount by 1.",
        "real_text": "<b>Interrupt</b> <i>(defense)</i>: When a hero would take any amount of damage, reduce that amount by 1.",
        "quantity": 3,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Defense.",
        "real_traits": "Defense.",
        "flavor": "\"Incoming!\" — Iron Man",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "a85dbb1d-e5ba-4f6b-8276-1f911f8ea1bd",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09021",
        "imagesrc": "/bundles/cards/09021.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "resource",
        "type_name": "Resource",
        "faction_code": "basic",
        "faction_name": "Basic",
        "duplicate_of_code": "01088",
        "duplicate_of_name": "Energy",
        "position": 22,
        "code": "09022",
        "name": "Energy",
        "real_name": "Energy",
        "text": "Max 1 per deck.",
        "real_text": "Max 1 per deck.",
        "quantity": 1,
        "resource_energy": 2,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "dd796868-b224-4ec0-be8f-46507c86cbef",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09022"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "resource",
        "type_name": "Resource",
        "faction_code": "basic",
        "faction_name": "Basic",
        "duplicate_of_code": "01089",
        "duplicate_of_name": "Genius",
        "position": 23,
        "code": "09023",
        "name": "Genius",
        "real_name": "Genius",
        "text": "Max 1 per deck.",
        "real_text": "Max 1 per deck.",
        "quantity": 1,
        "resource_mental": 2,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "ec9d5930-031c-493c-920b-32d980409567",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09023"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "resource",
        "type_name": "Resource",
        "faction_code": "basic",
        "faction_name": "Basic",
        "duplicate_of_code": "01090",
        "duplicate_of_name": "Strength",
        "position": 24,
        "code": "09024",
        "name": "Strength",
        "real_name": "Strength",
        "text": "Max 1 per deck.",
        "real_text": "Max 1 per deck.",
        "quantity": 1,
        "resource_physical": 2,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "a3fcb7fc-5fbf-4566-b29f-4abdd841e2cc",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09024"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "basic",
        "faction_name": "Basic",
        "duplicate_of_code": "01091",
        "duplicate_of_name": "Avengers Mansion",
        "position": 25,
        "code": "09025",
        "name": "Avengers Mansion",
        "real_name": "Avengers Mansion",
        "cost": 4,
        "text": "Max 1 per player.\n<b>Action</b>: Exhaust Avengers Mansion → choose a player. That player draws 1 card.",
        "real_text": "Max 1 per player.\n<b>Action</b>: Exhaust Avengers Mansion → choose a player. That player draws 1 card.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Avenger. Location.",
        "real_traits": "Avenger. Location.",
        "flavor": "\"Did you remember to turn off the stove?\" — Janet Van Dyne",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "f5ab3190-a2d1-4f1f-be25-de0085706eff",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09025"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 26,
        "code": "09026",
        "name": "The Sorcerer Supreme",
        "real_name": "The Sorcerer Supreme",
        "cost": 2,
        "text": "Play only if you have the [[Mystic]] trait.\nYou get +1 hand size while in hero form.",
        "real_text": "Play only if you have the [[Mystic]] trait.\nYou get +1 hand size while in hero form.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Title.",
        "real_traits": "Title.",
        "flavor": "\"The mantle of Sorcerer Supreme was bestowed upon me by the Ancient One.\" — Stephen Strange",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "b63402ba-906e-4119-a302-4a8dac229df0",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09026",
        "imagesrc": "/bundles/cards/09026.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "obligation",
        "type_name": "Obligation",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "doctor_strange",
        "card_set_name": "Doctor Strange",
        "card_set_type_name_code": "hero",
        "position": 27,
        "code": "09027",
        "name": "Physical Toll",
        "real_name": "Physical Toll",
        "text": "<b><i>Give to the Stephen Strange player.</i></b>\nYou may flip to alter-ego form. Choose:\n• Exhaust Stephen Strange → remove Physical Toll from the game.\n• The next event you play costs 3 additional resources. Discard this obligation after you play an event.",
        "real_text": "<b><i>Give to the Stephen Strange player.</i></b>\nYou may flip to alter-ego form. Choose:\n• Exhaust Stephen Strange → remove Physical Toll from the game.\n• The next event you play costs 3 additional resources. Discard this obligation after you play an event.",
        "boost": 2,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "illustrator": "Scott Drummond",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "a3f7ee13-c540-445b-b7d2-aad25d05a241",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09027",
        "imagesrc": "/bundles/cards/09027.png",
        "spoiler": 1
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "doctor_strange_nemesis",
        "card_set_name": "Doctor Strange Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 28,
        "set_position": 1,
        "code": "09028",
        "name": "Baron Mordo",
        "real_name": "Baron Mordo",
        "text": "<b>Forced Interrupt</b>: When Baron Mordo attacks you, discard the top card of your deck. If that card's printed resource has:\n[physical] - You are stunned.\n[energy] - Take 2 damage.\n[mental] - You are confused.\n[wild] - All of the above.",
        "real_text": "<b>Forced Interrupt</b>: When Baron Mordo attacks you, discard the top card of your deck. If that card's printed resource has:\n[physical] - You are stunned.\n[energy] - Take 2 damage.\n[mental] - You are confused.\n[wild] - All of the above.",
        "boost": 2,
        "quantity": 1,
        "health": 5,
        "health_per_hero": false,
        "scheme": 2,
        "attack": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Elite. Mystic.",
        "real_traits": "Elite. Mystic.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "b252f44b-3bf0-483d-8775-02c0b090117b",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09028",
        "imagesrc": "/bundles/cards/09028.png",
        "spoiler": 1
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "side_scheme",
        "type_name": "Side Scheme",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "doctor_strange_nemesis",
        "card_set_name": "Doctor Strange Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 29,
        "set_position": 2,
        "code": "09029",
        "name": "Open the Dark Dimension",
        "real_name": "Open the Dark Dimension",
        "text": "<b>When Revealed</b>: Place the top card of the [[Invocation]] deck facedown under this scheme.\n<b>When Defeated</b>: Shuffle the [[Invocation]] card under here into the [[Invocation]] deck.",
        "real_text": "<b>When Revealed</b>: Place the top card of the [[Invocation]] deck facedown under this scheme.\n<b>When Defeated</b>: Shuffle the [[Invocation]] card under here into the [[Invocation]] deck.",
        "boost": 3,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat": 3,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "scheme_acceleration": 1,
        "threat_fixed": false,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "98f64f7b-1fdd-4975-bd29-fc22d38abdd2",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09029",
        "imagesrc": "/bundles/cards/09029.png",
        "spoiler": 1
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "attachment",
        "type_name": "Attachment",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "doctor_strange_nemesis",
        "card_set_name": "Doctor Strange Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 30,
        "set_position": 3,
        "code": "09030",
        "name": "Counterspell",
        "real_name": "Counterspell",
        "text": "Attach to your hero.\n<b>Forced Interrupt</b>: When you play an event, cancel its effects and discard it. Then, discard this card.",
        "real_text": "Attach to your hero.\n<b>Forced Interrupt</b>: When you play an event, cancel its effects and discard it. Then, discard this card.",
        "boost": 1,
        "quantity": 2,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Condition. Spell.",
        "real_traits": "Condition. Spell.",
        "flavor": "\"I should have been made Sorcerer Supreme, Strange. Not you!\" — Baron Mordo.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "96162082-c6e2-403f-bb95-8717f019288f",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09030",
        "imagesrc": "/bundles/cards/09030.png",
        "spoiler": 1
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "treachery",
        "type_name": "Treachery",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "doctor_strange_nemesis",
        "card_set_name": "Doctor Strange Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 31,
        "set_position": 5,
        "code": "09031",
        "name": "Thoughtcasting",
        "real_name": "Thoughtcasting",
        "text": "<b>When Revealed (Alter-Ego)</b>: Discard a card from your hand with the highest cost. Place threat on the main scheme equal to the printed cost of that card.\n<b>When Revealed (Hero)</b>: Discard a card from your hand with the highest cost. Take damage equal to the printed cost of that card.",
        "real_text": "<b>When Revealed (Alter-Ego)</b>: Discard a card from your hand with the highest cost. Place threat on the main scheme equal to the printed cost of that card.\n<b>When Revealed (Hero)</b>: Discard a card from your hand with the highest cost. Take damage equal to the printed cost of that card.",
        "boost": 1,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "3ec62369-c299-4bf6-80ed-b4e479cebd38",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09031",
        "imagesrc": "/bundles/cards/09031.png",
        "spoiler": 1
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "invocation",
        "card_set_name": "Invocation",
        "card_set_type_name_code": "hero",
        "position": 32,
        "set_position": 1,
        "code": "09032",
        "name": "Crimson Bands of Cyttorak",
        "real_name": "Crimson Bands of Cyttorak",
        "cost": 2,
        "text": "<b>Special</b>: Stun an enemy and deal 7 damage to it. Place this card in the [[Invocation]] deck discard pile.",
        "real_text": "<b>Special</b>: Stun an enemy and deal 7 damage to it. Place this card in the [[Invocation]] deck discard pile.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Invocation.",
        "real_traits": "Invocation.",
        "flavor": "\"That should hold him for a spell.\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "097aa2dd-46d6-4240-93fe-f75ee826c200",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09032",
        "imagesrc": "/bundles/cards/09032.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "invocation",
        "card_set_name": "Invocation",
        "card_set_type_name_code": "hero",
        "position": 33,
        "set_position": 2,
        "code": "09033",
        "name": "Images of Ikonn",
        "real_name": "Images of Ikonn",
        "cost": 1,
        "text": "<b>Special</b>: Confuse the villain and remove 4 threat from a scheme. Place this card in the [[Invocation]] deck discard pile.",
        "real_text": "<b>Special</b>: Confuse the villain and remove 4 threat from a scheme. Place this card in the [[Invocation]] deck discard pile.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Invocation.",
        "real_traits": "Invocation.",
        "flavor": "\"You see only what I want you to see.\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "e13d7edc-562c-4172-b877-cdd66df212dd",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09033",
        "imagesrc": "/bundles/cards/09033.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "invocation",
        "card_set_name": "Invocation",
        "card_set_type_name_code": "hero",
        "position": 34,
        "set_position": 3,
        "code": "09034",
        "name": "Seven Rings of Raggadorr",
        "real_name": "Seven Rings of Raggadorr",
        "cost": 1,
        "text": "<b>Special</b>: Give up to 3 characters each a tough status card. Place this card in the [[Invocation]] deck discard pile.",
        "real_text": "<b>Special</b>: Give up to 3 characters each a tough status card. Place this card in the [[Invocation]] deck discard pile.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Invocation.",
        "real_traits": "Invocation.",
        "flavor": "\"Let the Rings of Raggadorr shield you from harm!\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "e91bb3dd-a827-487d-b552-09a3a9498e07",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09034",
        "imagesrc": "/bundles/cards/09034.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "invocation",
        "card_set_name": "Invocation",
        "card_set_type_name_code": "hero",
        "position": 35,
        "set_position": 4,
        "code": "09035",
        "name": "Vapors of Valtorr",
        "real_name": "Vapors of Valtorr",
        "cost": 0,
        "text": "<b>Special</b>: Choose a status card in play. Replace that status card with a different status card. Place this card in the [[Invocation]] deck discard pile.",
        "real_text": "<b>Special</b>: Choose a status card in play. Replace that status card with a different status card. Place this card in the [[Invocation]] deck discard pile.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Invocation.",
        "real_traits": "Invocation.",
        "flavor": "\"By the Vapors of Valtorr, be transformed!\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "f7c24523-44cf-4386-bb8f-7915fa6653b2",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09035",
        "imagesrc": "/bundles/cards/09035.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "invocation",
        "card_set_name": "Invocation",
        "card_set_type_name_code": "hero",
        "position": 36,
        "set_position": 5,
        "code": "09036",
        "name": "Winds of Watoomb",
        "real_name": "Winds of Watoomb",
        "cost": 0,
        "text": "<b>Special</b>: Draw 3 cards. Place this card in the [[Invocation]] deck discard pile.",
        "real_text": "<b>Special</b>: Draw 3 cards. Place this card in the [[Invocation]] deck discard pile.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Invocation.",
        "real_traits": "Invocation.",
        "flavor": "\"By the blessed Vishanti!\" — Doctor Strange",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "cf20b493-76f0-45c9-9709-4eb29b91f80d",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09036",
        "imagesrc": "/bundles/cards/09036.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "aggression",
        "faction_name": "Aggression",
        "position": 37,
        "code": "09037",
        "name": "Skilled Strike",
        "real_name": "Skilled Strike",
        "cost": 0,
        "text": "<b>Interrupt</b>: When your hero makes a basic attack, it gets +2 ATK for that attack.",
        "real_text": "<b>Interrupt</b>: When your hero makes a basic attack, it gets +2 ATK for that attack.",
        "quantity": 3,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Skill.",
        "real_traits": "Skill.",
        "flavor": "\"You have much to learn.\" — Karnak",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "41e072f8-3735-48dd-800e-8e078060797a",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09037",
        "imagesrc": "/bundles/cards/09037.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "justice",
        "faction_name": "Justice",
        "position": 38,
        "code": "09038",
        "name": "Foiled!",
        "real_name": "Foiled!",
        "cost": 0,
        "text": "<b>Interrupt</b>: When a boost card is turned faceup during a scheme activation, cancel its boost icons.",
        "real_text": "<b>Interrupt</b>: When a boost card is turned faceup during a scheme activation, cancel its boost icons.",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "flavor": "\"Not this time, Kingpin!\" — Spider-Man",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "bff7d04b-37c7-43c8-949a-5d1410b0b46d",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09038",
        "imagesrc": "/bundles/cards/09038.png"
    },
    {
        "pack_code": "drs",
        "pack_name": "Doctor Strange",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "leadership",
        "faction_name": "Leadership",
        "position": 39,
        "code": "09039",
        "name": "Iron Man",
        "real_name": "Iron Man",
        "subname": "Tony Stark",
        "cost": 4,
        "text": "Reduce the cost to play each upgrade on Iron Man by 1.",
        "real_text": "Reduce the cost to play each upgrade on Iron Man by 1.",
        "quantity": 1,
        "resource_wild": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 2,
        "thwart_cost": 1,
        "attack": 2,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Avenger.",
        "real_traits": "Avenger.",
        "flavor": "\"I've got an idea for how to make this suit even better.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "f5a2d616-e2a4-496e-987c-b35541ebc732",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/09039",
        "imagesrc": "/bundles/cards/09039.png"
    }
]