import { CardJson } from "../app/models/card.json";

export const spdrCards: CardJson[] = [
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "alter_ego",
        "type_name": "Alter-Ego",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "linked_to_code": "31002b",
        "linked_to_name": "SP//dr",
        "position": 2,
        "code": "31002a",
        "name": "Peni Parker",
        "real_name": "Peni Parker",
        "text": "<i>Psychogenetic Compatibility</i> — <b>Setup</b>: Put SP//dr Suit into play, [[Inactive]] side faceup.\n<i>Maintenance</i> — <b>Alter-Ego Action</b>: Exhaust SP//dr Suit → draw 2 cards.",
        "real_text": "<i>Psychogenetic Compatibility</i> — <b>Setup</b>: Put SP//dr Suit into play, [[Inactive]] side faceup.\n<i>Maintenance</i> — <b>Alter-Ego Action</b>: Exhaust SP//dr Suit → draw 2 cards.",
        "quantity": 1,
        "hand_size": 4,
        "health": 14,
        "health_per_hero": false,
        "recover": 4,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Civilian.",
        "real_traits": "Civilian.",
        "is_unique": true,
        "hidden": true,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031002",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31002a",
        "imagesrc": "/bundles/cards/31002a.png",
        "linked_card": {
            "pack_code": "spdr",
            "pack_name": "SP//dr",
            "type_code": "upgrade",
            "type_name": "Upgrade",
            "faction_code": "hero",
            "faction_name": "Hero",
            "card_set_code": "spdr",
            "card_set_name": "SP//dr",
            "card_set_type_name_code": "hero",
            "id": 1931,
            "position": 2,
            "set_position": 2,
            "code": "31002b",
            "name": "SP//dr",
            "real_name": "SP//dr",
            "subname": null,
            "cost": null,
            "text": "<p>Permanent. This card's printed text box cannot be treated as if it were blank.</p><p><i>Suit Up!</i> — <b>Forced Interrupt</b>: When you flip to this side, flip SP//dr Suit to its <b class=\"card-traits\"><i>Active</i></b> side. Attach this card to SP//dr Suit, moving all counters on this cards or cards attached to this card to SP//dr Suit.</p>",
            "real_text": "Permanent. This card's printed text box cannot be treated as if it were blank.\n<i>Suit Up!</i> — <b>Forced Interrupt</b>: When you flip to this side, flip SP//dr Suit to its [[Active]] side. Attach this card to SP//dr Suit, moving all counters on this cards or cards attached to this card to SP//dr Suit.",
            "boost": null,
            "quantity": 1,
            "resource_energy": null,
            "resource_physical": null,
            "resource_mental": null,
            "resource_wild": 1,
            "hand_size": null,
            "health": null,
            "health_per_hero": false,
            "thwart": null,
            "thwart_cost": null,
            "scheme": null,
            "attack": null,
            "attack_cost": null,
            "defense": null,
            "defense_cost": null,
            "recover": null,
            "recover_cost": null,
            "base_threat": null,
            "base_threat_fixed": false,
            "escalation_threat": null,
            "escalation_threat_fixed": false,
            "scheme_crisis": null,
            "scheme_acceleration": null,
            "scheme_hazard": null,
            "threat": null,
            "threat_fixed": false,
            "deck_limit": 1,
            "stage": null,
            "traits": "Interface. Pilot.",
            "real_traits": "Interface. Pilot.",
            "meta": null,
            "deck_requirements": null,
            "deck_options": null,
            "restrictions": null,
            "flavor": "",
            "illustrator": null,
            "is_unique": true,
            "hidden": true,
            "permanent": false,
            "double_sided": false,
            "back_text": null,
            "back_flavor": null,
            "back_name": null,
            "octgn_id": "5b7da011-412e-452a-9edd-24618a031002",
            "attack_star": false,
            "thwart_star": false,
            "defense_star": false,
            "health_star": false,
            "recover_star": false,
            "scheme_star": false,
            "boost_star": false,
            "threat_star": false,
            "escalation_threat_star": false,
            "url": "https://marvelcdb.com/card/31002b",
            "imagesrc": "/bundles/cards/31002b.png",
            "backimagesrc": null
        }
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "hero",
        "type_name": "Hero",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "linked_to_code": "31001b",
        "linked_to_name": "SP//dr Suit",
        "position": 1,
        "code": "31001a",
        "name": "SP//dr Suit",
        "real_name": "SP//dr Suit",
        "text": "<i>Sync Ratio</i> — <b>Resource</b>: Exhaust an [[Interface]] upgrade you control → generate that upgrade's resources.",
        "real_text": "<i>Sync Ratio</i> — <b>Resource</b>: Exhaust an [[Interface]] upgrade you control → generate that upgrade's resources.",
        "quantity": 1,
        "hand_size": 3,
        "health": 14,
        "health_per_hero": false,
        "thwart": 2,
        "attack": 2,
        "defense": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Active. Web-Warrior.",
        "real_traits": "Active. Web-Warrior.",
        "meta": {
            "colors": [
                "#7a7d7f",
                "#9f1c2e",
                "#fdb912",
                "#fffffd"
            ]
        },
        "flavor": "\"We're called SP//dr, and we protect the city.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031001",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31001a",
        "imagesrc": "/bundles/cards/31001a.png",
        "linked_card": {
            "pack_code": "spdr",
            "pack_name": "SP//dr",
            "type_code": "support",
            "type_name": "Support",
            "faction_code": "hero",
            "faction_name": "Hero",
            "card_set_code": "spdr",
            "card_set_name": "SP//dr",
            "card_set_type_name_code": "hero",
            "id": 1929,
            "position": 1,
            "set_position": 1,
            "code": "31001b",
            "name": "SP//dr Suit",
            "real_name": "SP//dr Suit",
            "subname": null,
            "cost": null,
            "text": "<p>Permanent. This card's printed text box cannot be treated as if it were blank.</p><p><i>Return to Base</i> — <b>Forced Interrupt</b>: When you flip to this side, flip SP//dr to Peni Parker. Detach Peni Parker from here, moving all counters on her and cards attached to her to this card.</p>",
            "real_text": "Permanent. This card's printed text box cannot be treated as if it were blank.\n<i>Return to Base</i> — <b>Forced Interrupt</b>: When you flip to this side, flip SP//dr to Peni Parker. Detach Peni Parker from here, moving all counters on her and cards attached to her to this card.",
            "boost": null,
            "quantity": 1,
            "resource_energy": null,
            "resource_physical": null,
            "resource_mental": null,
            "resource_wild": null,
            "hand_size": null,
            "health": null,
            "health_per_hero": false,
            "thwart": null,
            "thwart_cost": null,
            "scheme": null,
            "attack": null,
            "attack_cost": null,
            "defense": null,
            "defense_cost": null,
            "recover": null,
            "recover_cost": null,
            "base_threat": null,
            "base_threat_fixed": false,
            "escalation_threat": null,
            "escalation_threat_fixed": false,
            "scheme_crisis": null,
            "scheme_acceleration": null,
            "scheme_hazard": null,
            "threat": null,
            "threat_fixed": false,
            "deck_limit": 1,
            "stage": null,
            "traits": "Inactive. Tech.",
            "real_traits": "Inactive. Tech.",
            "meta": null,
            "deck_requirements": null,
            "deck_options": null,
            "restrictions": null,
            "flavor": "",
            "illustrator": null,
            "is_unique": true,
            "hidden": true,
            "permanent": false,
            "double_sided": false,
            "back_text": null,
            "back_flavor": null,
            "back_name": null,
            "octgn_id": "5b7da011-412e-452a-9edd-24618a031001",
            "attack_star": false,
            "thwart_star": false,
            "defense_star": false,
            "health_star": false,
            "recover_star": false,
            "scheme_star": false,
            "boost_star": false,
            "threat_star": false,
            "escalation_threat_star": false,
            "url": "https://marvelcdb.com/card/31001b",
            "imagesrc": "/bundles/cards/31001b.png",
            "backimagesrc": null
        }
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 3,
        "set_position": 3,
        "code": "31003",
        "name": "VEN#m",
        "real_name": "VEN#m",
        "subname": "Addy Brock",
        "cost": 4,
        "text": "[star] VEN#m gets +1 THW and +1 ATK for each sym counter on her.\n<b>Hero Response</b>: After VEN#m enters play, place 1 sym counter on her for each resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability to pay for her.",
        "real_text": "[star] VEN#m gets +1 THW and +1 ATK for each sym counter on her.\n<b>Hero Response</b>: After VEN#m enters play, place 1 sym counter on her for each resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability to pay for her.",
        "quantity": 1,
        "resource_energy": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 1,
        "thwart_cost": 1,
        "attack": 1,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031003",
        "attack_star": true,
        "thwart_star": true,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31003",
        "imagesrc": "/bundles/cards/31003.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 4,
        "set_position": 4,
        "code": "31004",
        "name": "All Systems Go!",
        "real_name": "All Systems Go!",
        "cost": 1,
        "text": "<b>Hero Action</b>: Choose:\n• Ready each [[Interface]] upgrade you control.\n• Search your deck and discard pile for an [[Interface]] upgrade and add it to your hand. (Shuffle.)",
        "real_text": "<b>Hero Action</b>: Choose:\n• Ready each [[Interface]] upgrade you control.\n• Search your deck and discard pile for an [[Interface]] upgrade and add it to your hand. (Shuffle.)",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031004",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31004",
        "imagesrc": "/bundles/cards/31004.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 5,
        "set_position": 7,
        "code": "31005",
        "name": "Rapid Deployment",
        "real_name": "Rapid Deployment",
        "cost": 2,
        "text": "<b>Hero Action</b> <i>(thwart)</i>: Remove 3 threat from a scheme. If you paid for this card using a resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability, remove 3 threat from a scheme.",
        "real_text": "<b>Hero Action</b> <i>(thwart)</i>: Remove 3 threat from a scheme. If you paid for this card using a resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability, remove 3 threat from a scheme.",
        "quantity": 2,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "traits": "Thwart.",
        "real_traits": "Thwart.",
        "flavor": "\"We'll protect this city, no matter what.\" —SP//dr",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031005",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31005",
        "imagesrc": "/bundles/cards/31005.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 6,
        "set_position": 9,
        "code": "31006",
        "name": "Web-Trap",
        "real_name": "Web-Trap",
        "cost": 2,
        "text": "<b>Hero Action</b> <i>(attack)</i>: Deal 5 damage to an enemy. If you paid for this card using a resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability, stun that enemy.",
        "real_text": "<b>Hero Action</b> <i>(attack)</i>: Deal 5 damage to an enemy. If you paid for this card using a resource generated by SP//dr Suit's <i>\"Sync Ratio\"</i> ability, stun that enemy.",
        "quantity": 2,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 2,
        "traits": "Attack.",
        "real_traits": "Attack.",
        "flavor": "\"May wanted SP//dr to be better, to be the best we could. That's why she developed these web-traps!\"",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031006",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31006",
        "imagesrc": "/bundles/cards/31006.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 7,
        "set_position": 11,
        "code": "31007",
        "name": "Aunt May & Uncle Ben",
        "real_name": "Aunt May & Uncle Ben",
        "cost": 1,
        "text": "<b>Action</b>: Exhaust Aunt May & Uncle Ben and discard the top 2 cards of your deck (top 3 cards instead if you are in alter-ego form) → add each SP//dr card discarded this way to your hand.",
        "real_text": "<b>Action</b>: Exhaust Aunt May & Uncle Ben and discard the top 2 cards of your deck (top 3 cards instead if you are in alter-ego form) → add each SP//dr card discarded this way to your hand.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Persona.",
        "real_traits": "Persona.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031007",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31007",
        "imagesrc": "/bundles/cards/31007.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 8,
        "set_position": 12,
        "code": "31008",
        "name": "Ejection Protocol",
        "real_name": "Ejection Protocol",
        "cost": 0,
        "text": "<b>Hero Action</b>: Discard Ejection Protocol → exhaust each [[Interface]] upgrade you control, set your hit point dial to 6, give your identity a tough status card, and flip to alter-ego form.",
        "real_text": "<b>Hero Action</b>: Discard Ejection Protocol → exhaust each [[Interface]] upgrade you control, set your hit point dial to 6, give your identity a tough status card, and flip to alter-ego form.",
        "quantity": 1,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Tactic.",
        "real_traits": "Tactic.",
        "flavor": "\"Warning! Incoming threat!\"",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031008",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31008",
        "imagesrc": "/bundles/cards/31008.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "support",
        "type_name": "Support",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 9,
        "set_position": 13,
        "code": "31009",
        "name": "SP//dr Command",
        "real_name": "SP//dr Command",
        "cost": 1,
        "text": "<b>Hero Action</b>: Exhaust SP//dr Command and an [[Interface]] upgrade → draw 1 card.\n<b>Hero Action</b>: Exhaust SP//dr Command, choose and discard 1 card from your hand → ready an [[Interface]] upgrade.",
        "real_text": "<b>Hero Action</b>: Exhaust SP//dr Command and an [[Interface]] upgrade → draw 1 card.\n<b>Hero Action</b>: Exhaust SP//dr Command, choose and discard 1 card from your hand → ready an [[Interface]] upgrade.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Location.",
        "real_traits": "Location.",
        "flavor": "\"Peni, listen to our orders very carefully.\"",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031009",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31009",
        "imagesrc": "/bundles/cards/31009.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 10,
        "set_position": 14,
        "code": "31010",
        "name": "Host Spider",
        "real_name": "Host Spider",
        "cost": 3,
        "text": "<b>Hero Action</b>: Exhaust Host Spider → ready SP//dr Suit.",
        "real_text": "<b>Hero Action</b>: Exhaust Host Spider → ready SP//dr Suit.",
        "quantity": 1,
        "resource_wild": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Interface. Spider.",
        "real_traits": "Interface. Spider.",
        "flavor": "\"He trusts you… so will I.\" —Peni Parker",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031010",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31010",
        "imagesrc": "/bundles/cards/31010.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 11,
        "set_position": 15,
        "code": "31011",
        "name": "Psychic Link",
        "real_name": "Psychic Link",
        "cost": 2,
        "text": "<b>Hero Interrupt</b>: When SP//dr Suit makes a basic thwart, exhaust Psychic Link → it gets +2 THW for that thwart.",
        "real_text": "<b>Hero Interrupt</b>: When SP//dr Suit makes a basic thwart, exhaust Psychic Link → it gets +2 THW for that thwart.",
        "quantity": 1,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Interface. Tech.",
        "real_traits": "Interface. Tech.",
        "flavor": "\"Can we listen to music? It helps us focus.\" —Peni Parker",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031011",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31011",
        "imagesrc": "/bundles/cards/31011.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 12,
        "set_position": 16,
        "code": "31012",
        "name": "Speed-Metal Alloy",
        "real_name": "Speed-Metal Alloy",
        "cost": 1,
        "text": "<b>Hero Interrupt</b>: When SP//dr Suit defends against an attack, exhaust Speed-Metal Alloy → it gets +2 DEF for that defense.",
        "real_text": "<b>Hero Interrupt</b>: When SP//dr Suit defends against an attack, exhaust Speed-Metal Alloy → it gets +2 DEF for that defense.",
        "quantity": 1,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Interface. Tech.",
        "real_traits": "Interface. Tech.",
        "flavor": "\"I thought you said it was a suit—this is speed-metal!\" —Spider-Ham",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031012",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31012",
        "imagesrc": "/bundles/cards/31012.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "hero",
        "faction_name": "Hero",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 13,
        "set_position": 17,
        "code": "31013",
        "name": "Web-Fluid Compressor",
        "real_name": "Web-Fluid Compressor",
        "cost": 2,
        "text": "<b>Hero Interrupt</b>: When SP/dr Suit makes a basic attack, exhaust Web-Fluid Compressor → it gets +2 ATK for that attack.",
        "real_text": "<b>Hero Interrupt</b>: When SP/dr Suit makes a basic attack, exhaust Web-Fluid Compressor → it gets +2 ATK for that attack.",
        "quantity": 1,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Interface. Tech.",
        "real_traits": "Interface. Tech.",
        "flavor": "\"Progress takes patience. That's why we have to keep working on it.\" —Aunt May",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031013",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31013",
        "imagesrc": "/bundles/cards/31013.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 14,
        "code": "31014",
        "name": "Daredevil",
        "real_name": "Daredevil",
        "cost": 2,
        "text": "<b>Response</b>: After Daredevil defends against an attack, move 1 damage from him to the attacking enemy.",
        "real_text": "<b>Response</b>: After Daredevil defends against an attack, move 1 damage from him to the attacking enemy.",
        "quantity": 1,
        "resource_physical": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 2,
        "thwart_cost": 2,
        "attack": 1,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "flavor": "\"Quiet breaks, shatters down, so the city reaches out. Listening… Waiting… Another station for a signal, and we're all some kind of noise. Be the good kind, Peni.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031014",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31014",
        "imagesrc": "/bundles/cards/31014.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 15,
        "code": "31015",
        "name": "Spider-Man Noir",
        "real_name": "Spider-Man Noir",
        "cost": 3,
        "text": "X is equal to the number of facedown cards attached to Spider-Man Noir.\n<b>Response</b>: After you resolve a treachery, if you control another [[Web-Warrior]] card, attach that treachery facedown here (to a maximum of 3).",
        "real_text": "X is equal to the number of facedown cards attached to Spider-Man Noir.\n<b>Response</b>: After you resolve a treachery, if you control another [[Web-Warrior]] card, attach that treachery facedown here (to a maximum of 3).",
        "quantity": 1,
        "resource_energy": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": -1,
        "thwart_cost": 1,
        "attack": -1,
        "attack_cost": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Web-Warrior.",
        "real_traits": "Web-Warrior.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031015",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31015",
        "imagesrc": "/bundles/cards/31015.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 16,
        "code": "31016",
        "name": "Repurpose",
        "real_name": "Repurpose",
        "cost": 0,
        "text": "<b>Hero Action</b>: Discard a [[Tech]] upgrade you control → ready your hero and choose THW, ATK, or DEF. Until the end of the round, your hero gets +X to the chosen power, where X is equal to that upgrade's printed cost.",
        "real_text": "<b>Hero Action</b>: Discard a [[Tech]] upgrade you control → ready your hero and choose THW, ATK, or DEF. Until the end of the round, your hero gets +X to the chosen power, where X is equal to that upgrade's printed cost.",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Skill.",
        "real_traits": "Skill.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031016",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31016",
        "imagesrc": "/bundles/cards/31016.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 17,
        "code": "31017",
        "name": "Thwip! Thwip!",
        "real_name": "Thwip! Thwip!",
        "cost": 2,
        "text": "<b>Hero Action</b>: Deal 1 damage to a [[Web-Warrior]] character you control → place a total of 2 stun status cards on up to 2 enemies.",
        "real_text": "<b>Hero Action</b>: Deal 1 damage to a [[Web-Warrior]] character you control → place a total of 2 stun status cards on up to 2 enemies.",
        "quantity": 3,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Superpower.",
        "real_traits": "Superpower.",
        "flavor": "\"You now have the entire afternoon to reconsider your life choices. You're welcome.\" —Spider-Man",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031017",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31017",
        "imagesrc": "/bundles/cards/31017.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "protection",
        "faction_name": "Protection",
        "duplicate_of_code": "05017",
        "duplicate_of_name": "Energy Barrier",
        "position": 18,
        "code": "31018",
        "name": "Energy Barrier",
        "real_name": "Energy Barrier",
        "cost": 2,
        "text": "Uses (3 reflection counters). <b>Interrupt:</b> When you would take any amount of damage, remove 1 reflection counter from here → prevent 1 of that damage and deal 1 damage to an enemy.",
        "real_text": "Uses (3 reflection counters). <b>Interrupt:</b> When you would take any amount of damage, remove 1 reflection counter from here → prevent 1 of that damage and deal 1 damage to an enemy.",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Item. Tech.",
        "real_traits": "Item. Tech.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "9738f524-63e0-4053-a26e-0ec8cdedf8e3",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31018"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 19,
        "code": "31019",
        "name": "Forcefield Generator",
        "real_name": "Forcefield Generator",
        "cost": 3,
        "text": "Uses (6 energy counters). Max 1 per player.\n<b>Forced Interrupt</b>: When you would take any amount of damage, remove that many energy counters from here. For each energy counter removed this way, prevent 1 of that damage.",
        "real_text": "Uses (6 energy counters). Max 1 per player.\n<b>Forced Interrupt</b>: When you would take any amount of damage, remove that many energy counters from here. For each energy counter removed this way, prevent 1 of that damage.",
        "quantity": 3,
        "resource_energy": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Tech.",
        "real_traits": "Tech.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031019",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31019",
        "imagesrc": "/bundles/cards/31019.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "protection",
        "faction_name": "Protection",
        "position": 20,
        "code": "31020",
        "name": "Spider-Tingle",
        "real_name": "Spider-Tingle",
        "cost": 1,
        "text": "<b>Interrupt</b>: When you would reveal an encounter card, deal 1 damage to a [[Web-Warrior]] character you control → if that card is a treachery, cancel its <b>\"When Revealed\"</b> effects and discard Spider-Tingle.",
        "real_text": "<b>Interrupt</b>: When you would reveal an encounter card, deal 1 damage to a [[Web-Warrior]] character you control → if that card is a treachery, cancel its <b>\"When Revealed\"</b> effects and discard Spider-Tingle.",
        "quantity": 3,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Superpower.",
        "real_traits": "Superpower.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031020",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31020",
        "imagesrc": "/bundles/cards/31020.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 21,
        "code": "31021",
        "name": "Spider-Ham",
        "real_name": "Spider-Ham",
        "subname": "Peter Porker",
        "cost": 3,
        "text": "Play only if you control a [[Web-Warrior]] card.\n[star] <b>Forced Response</b>: After Spider-Ham attacks or thwarts, discard the top card of the encounter deck. For each boost icon ([boost]) discarded this way, deal 1 damage to Spider-Ham.",
        "real_text": "Play only if you control a [[Web-Warrior]] card.\n[star] <b>Forced Response</b>: After Spider-Ham attacks or thwarts, discard the top card of the encounter deck. For each boost icon ([boost]) discarded this way, deal 1 damage to Spider-Ham.",
        "quantity": 1,
        "resource_physical": 1,
        "health": 3,
        "health_per_hero": false,
        "thwart": 2,
        "thwart_cost": 0,
        "attack": 2,
        "attack_cost": 0,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Cartoon. Web-Warrior.",
        "real_traits": "Cartoon. Web-Warrior.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031021",
        "attack_star": true,
        "thwart_star": true,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31021",
        "imagesrc": "/bundles/cards/31021.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "ally",
        "type_name": "Ally",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 22,
        "code": "31022",
        "name": "Spider-Man",
        "real_name": "Spider-Man",
        "subname": "Otto Octavius",
        "cost": 2,
        "text": "Play only if you control a [[Web-Warrior]] card.\n<b>Response</b>: After you play Spider-Man from your hand, ready an upgrade you control. If that upgrade has the [[Tech]] trait, draw 1 card.",
        "real_text": "Play only if you control a [[Web-Warrior]] card.\n<b>Response</b>: After you play Spider-Man from your hand, ready an upgrade you control. If that upgrade has the [[Tech]] trait, draw 1 card.",
        "quantity": 1,
        "resource_mental": 1,
        "health": 2,
        "health_per_hero": false,
        "thwart": 1,
        "thwart_cost": 1,
        "attack": 2,
        "attack_cost": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "traits": "Web-Warrior.",
        "real_traits": "Web-Warrior.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031022",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31022",
        "imagesrc": "/bundles/cards/31022.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "event",
        "type_name": "Event",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 23,
        "code": "31023",
        "name": "Limitless Stamina",
        "real_name": "Limitless Stamina",
        "cost": 1,
        "text": "Play only if your identity has at least 14 printed hit points.\n<b>Hero Action</b>: Ready your hero.",
        "real_text": "Play only if your identity has at least 14 printed hit points.\n<b>Hero Action</b>: Ready your hero.",
        "quantity": 3,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Superpower.",
        "real_traits": "Superpower.",
        "flavor": "\"What, you think this fight is almost over?! That was just warm-up practice.\" —Thor",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031023",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31023",
        "imagesrc": "/bundles/cards/31023.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "basic",
        "faction_name": "Basic",
        "position": 24,
        "code": "31024",
        "name": "Unshakable",
        "real_name": "Unshakable",
        "cost": 1,
        "text": "Play only if your identity has at least 14 printed hit points.\nYour identity gains steady.",
        "real_text": "Play only if your identity has at least 14 printed hit points.\nYour identity gains steady.",
        "quantity": 3,
        "resource_physical": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Condition. Superpower.",
        "real_traits": "Condition. Superpower.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031024",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31024",
        "imagesrc": "/bundles/cards/31024.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "obligation",
        "type_name": "Obligation",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "spdr",
        "card_set_name": "SP//dr",
        "card_set_type_name_code": "hero",
        "position": 25,
        "code": "31025",
        "name": "Inherited Burden",
        "real_name": "Inherited Burden",
        "text": "<b><i>Give to the Peni Parker player.</i></b>\nYou may flip to alter-ego form. Choose:\n• Exhaust Peni Parker → remove Inherited Burden from the game.\n• Choose and discard 1 [[Interface]] upgrade you control. Discard this obligation.",
        "real_text": "<b><i>Give to the Peni Parker player.</i></b>\nYou may flip to alter-ego form. Choose:\n• Exhaust Peni Parker → remove Inherited Burden from the game.\n• Choose and discard 1 [[Interface]] upgrade you control. Discard this obligation.",
        "boost": 2,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 1,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031025",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31025",
        "imagesrc": "/bundles/cards/31025.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "side_scheme",
        "type_name": "Side Scheme",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "spdr_nemesis",
        "card_set_name": "SP//dr Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 26,
        "set_position": 1,
        "code": "31026",
        "name": "Giant Monster Attack",
        "real_name": "Giant Monster Attack",
        "text": "As an additional cost to thwart this scheme, you must spend a [energy] resource.",
        "real_text": "As an additional cost to thwart this scheme, you must spend a [energy] resource.",
        "boost": 3,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat": 4,
        "base_threat_fixed": true,
        "escalation_threat_fixed": false,
        "scheme_crisis": 1,
        "threat_fixed": false,
        "flavor": "M.O.R.B.I.U.S. is laying siege to the city, wreaking havoc and siphoning energy from its power grid.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031026",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31026",
        "imagesrc": "/bundles/cards/31026.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "spdr_nemesis",
        "card_set_name": "SP//dr Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 27,
        "set_position": 2,
        "code": "31027",
        "name": "M.O.R.B.I.U.S.",
        "real_name": "M.O.R.B.I.U.S.",
        "text": "<b>Forced Response</b>: After the engaged hero generates any number of resources, deal an equal amount of damage to that hero.\n<i>(SP//dr's nemesis minion.)</i>",
        "real_text": "<b>Forced Response</b>: After the engaged hero generates any number of resources, deal an equal amount of damage to that hero.\n<i>(SP//dr's nemesis minion.)</i>",
        "boost": 2,
        "quantity": 1,
        "health": 6,
        "health_per_hero": false,
        "scheme": 2,
        "attack": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Creature.",
        "real_traits": "Creature.",
        "flavor": "\"This is a threat unlike any you've faced before!\" —Uncle Ben",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031027",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31027",
        "imagesrc": "/bundles/cards/31027.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "treachery",
        "type_name": "Treachery",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "spdr_nemesis",
        "card_set_name": "SP//dr Nemesis",
        "card_set_type_name_code": "nemesis",
        "position": 28,
        "set_position": 3,
        "code": "31028",
        "name": "Energy Drain",
        "real_name": "Energy Drain",
        "text": "<b>When Revealed (Alter-Ego)</b>: Choose to either spend [energy][energy] resources or exhaust your identity.\n<b>When Revealed (Hero)</b>: Choose to either spend [energy][energy] or take 3 damage.",
        "real_text": "<b>When Revealed (Alter-Ego)</b>: Choose to either spend [energy][energy] resources or exhaust your identity.\n<b>When Revealed (Hero)</b>: Choose to either spend [energy][energy] or take 3 damage.",
        "boost": 1,
        "quantity": 3,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031028",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31028",
        "imagesrc": "/bundles/cards/31028.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "upgrade",
        "type_name": "Upgrade",
        "faction_code": "leadership",
        "faction_name": "Leadership",
        "position": 29,
        "code": "31029",
        "name": "Clarity of Purpose",
        "real_name": "Clarity of Purpose",
        "cost": 1,
        "text": "Attach to a friendly character. Max 1 per character.\n<b>Hero Resource</b>: Exhaust this card and deal 1 damage to attached character → generate a [wild] resource.",
        "real_text": "Attach to a friendly character. Max 1 per character.\n<b>Hero Resource</b>: Exhaust this card and deal 1 damage to attached character → generate a [wild] resource.",
        "quantity": 3,
        "resource_mental": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "deck_limit": 3,
        "traits": "Condition.",
        "real_traits": "Condition.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031029",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31029",
        "imagesrc": "/bundles/cards/31029.png"
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "side_scheme",
        "type_name": "Side Scheme",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 30,
        "set_position": 1,
        "code": "31030",
        "name": "Grand Larceny",
        "real_name": "Grand Larceny",
        "text": "Threat cannot be removed from this scheme while a [[Criminal]] minion is in play.",
        "real_text": "Threat cannot be removed from this scheme while a [[Criminal]] minion is in play.",
        "boost": 3,
        "quantity": 1,
        "health_per_hero": false,
        "base_threat": 4,
        "base_threat_fixed": true,
        "escalation_threat_fixed": false,
        "scheme_crisis": 1,
        "threat_fixed": false,
        "flavor": "The Iron Spider's Sinister Six are on an crime spree, robbing every business they come across.",
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031030",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31030",
        "imagesrc": "/bundles/cards/31030.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 31,
        "set_position": 2,
        "code": "31031",
        "name": "Bombshell",
        "real_name": "Bombshell",
        "text": "[star] Divide damage from Bombshell's attack among each character the attacked player controls as evenly as possible.\n<hr />\n[star] <b>Boost</b>: Deal 1 indirect damage to each player. Exhaust each character damaged this way.",
        "real_text": "[star] Divide damage from Bombshell's attack among each character the attacked player controls as evenly as possible.\n<hr />\n[star] <b>Boost</b>: Deal 1 indirect damage to each player. Exhaust each character damaged this way.",
        "quantity": 1,
        "health": 4,
        "health_per_hero": false,
        "scheme": 2,
        "attack": 3,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal.",
        "real_traits": "Criminal.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031031",
        "attack_star": true,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": true,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31031",
        "imagesrc": "/bundles/cards/31031.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 32,
        "set_position": 3,
        "code": "31032",
        "name": "Electro",
        "real_name": "Electro",
        "text": "[star] Electro gets +1 hit point for each [energy] resource attached to her.\n[star] <b>Forced Response</b>: After Electro engages you or activates against you, choose 1 card from your hand with a printed [energy] resource and attach it to her.",
        "real_text": "[star] Electro gets +1 hit point for each [energy] resource attached to her.\n[star] <b>Forced Response</b>: After Electro engages you or activates against you, choose 1 card from your hand with a printed [energy] resource and attach it to her.",
        "boost": 1,
        "quantity": 1,
        "health": 3,
        "health_per_hero": false,
        "scheme": 1,
        "attack": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal.",
        "real_traits": "Criminal.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031032",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": true,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31032",
        "imagesrc": "/bundles/cards/31032.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 33,
        "set_position": 4,
        "code": "31033",
        "name": "Hobgoblin",
        "real_name": "Hobgoblin",
        "text": "[star] <b>Forced Interrupt</b>: When Hobgoblin would attack you, discard cards from the top of the encounter deck equal to Hobgoblin's ATK instead. Take 1 indirect damage for each boost icon ([boost]) discarded this way.",
        "real_text": "[star] <b>Forced Interrupt</b>: When Hobgoblin would attack you, discard cards from the top of the encounter deck equal to Hobgoblin's ATK instead. Take 1 indirect damage for each boost icon ([boost]) discarded this way.",
        "boost": 2,
        "quantity": 1,
        "health": 5,
        "health_per_hero": false,
        "scheme": 2,
        "attack": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal.",
        "real_traits": "Criminal.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031033",
        "attack_star": true,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31033",
        "imagesrc": "/bundles/cards/31033.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 34,
        "set_position": 5,
        "code": "31034",
        "name": "Iron Spider",
        "real_name": "Iron Spider",
        "text": "Guard. Patrol. Retaliate 1. Toughness.\n[star] Iron Spider's attacks gain overkill.",
        "real_text": "Guard. Patrol. Retaliate 1. Toughness.\n[star] Iron Spider's attacks gain overkill.",
        "boost": 3,
        "quantity": 1,
        "health": 6,
        "health_per_hero": false,
        "scheme": 2,
        "attack": 2,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal. Elite.",
        "real_traits": "Criminal. Elite.",
        "flavor": "\"Don't make me whoop you.\"",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031034",
        "attack_star": true,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31034",
        "imagesrc": "/bundles/cards/31034.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 35,
        "set_position": 6,
        "code": "31035",
        "name": "Sandman",
        "real_name": "Sandman",
        "text": "<b>Forced Response</b>: After Sandman takes any amount of damage from an attack, discard the top 7 cards of the encounter deck.\n<hr />\n[star] <b>Boost</b>: Discard the top 7 cards of the encounter deck.",
        "real_text": "<b>Forced Response</b>: After Sandman takes any amount of damage from an attack, discard the top 7 cards of the encounter deck.\n<hr />\n[star] <b>Boost</b>: Discard the top 7 cards of the encounter deck.",
        "boost": 1,
        "quantity": 1,
        "health": 7,
        "health_per_hero": false,
        "scheme": 1,
        "attack": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal.",
        "real_traits": "Criminal.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031035",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": true,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31035",
        "imagesrc": "/bundles/cards/31035.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "minion",
        "type_name": "Minion",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 36,
        "set_position": 7,
        "code": "31036",
        "name": "Spot",
        "real_name": "Spot",
        "text": "<b>When Defeated</b>: If Spot was defeated without excess damage, shuffle him into the encounter deck.\n<hr />\n[star] <b>Boost</b>: Put this minion into play engaged with you.",
        "real_text": "<b>When Defeated</b>: If Spot was defeated without excess damage, shuffle him into the encounter deck.\n<hr />\n[star] <b>Boost</b>: Put this minion into play engaged with you.",
        "quantity": 1,
        "health": 4,
        "health_per_hero": false,
        "scheme": 1,
        "attack": 1,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "traits": "Criminal.",
        "real_traits": "Criminal.",
        "is_unique": true,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031036",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": true,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31036",
        "imagesrc": "/bundles/cards/31036.png",
        "spoiler": 1
    },
    {
        "pack_code": "spdr",
        "pack_name": "SP//dr",
        "type_code": "environment",
        "type_name": "Environment",
        "faction_code": "encounter",
        "faction_name": "Encounter",
        "card_set_code": "ironspider_sinister",
        "card_set_name": "Iron Spider's Sinister Six",
        "card_set_type_name_code": "modular",
        "position": 37,
        "set_position": 8,
        "code": "31037",
        "name": "Surge in Crime",
        "real_name": "Surge in Crime",
        "text": "Surge.\nEach [[Criminal]] minion gains surge.\n<b>Hero Action</b>: If there are no [[Criminal]] minions in play, spend 2 resources of any type → discard this card.",
        "real_text": "Surge.\nEach [[Criminal]] minion gains surge.\n<b>Hero Action</b>: If there are no [[Criminal]] minions in play, spend 2 resources of any type → discard this card.",
        "quantity": 1,
        "health_per_hero": false,
        "base_threat_fixed": false,
        "escalation_threat_fixed": false,
        "threat_fixed": false,
        "is_unique": false,
        "hidden": false,
        "permanent": false,
        "double_sided": false,
        "octgn_id": "5b7da011-412e-452a-9edd-24618a031037",
        "attack_star": false,
        "thwart_star": false,
        "defense_star": false,
        "health_star": false,
        "recover_star": false,
        "scheme_star": false,
        "boost_star": false,
        "threat_star": false,
        "escalation_threat_star": false,
        "url": "https://marvelcdb.com/card/31037",
        "imagesrc": "/bundles/cards/31037.png",
        "spoiler": 1
    }
]